###
POST http://{{host}}:{{port}}/word/loadXiaShuoArticle
Content-Type: application/json

{   "startPage": 2, "endPage": 2 }

###
POST http://{{host}}:{{port}}/word/loadChinaDailyArticle
Content-Type: application/json

{   "model": {    } }

###
POST http://{{host}}:{{port}}/word/dictWordEn
Content-Type: application/json

{   "model": {    } }






