###
POST http://{{host}}:{{port}}/word/loadXiaShuoArticle
Content-Type: application/json

{ "model": { "articleLink":"/waiyu/3240558", "articleStartPage": 1, "articleEndPage": 1, "articleIndex": 1, "articleTitleList": ["把绿色理念变成商业","2"]} }

###
POST http://{{host}}:{{port}}/word/loadChinaDailyArticle
Content-Type: application/json

{ "model": { "articleLink":"/waiyu/14804689", "articleStartPage": 20, "articleEndPage": 20, "articleIndexList": [348]} }

###
POST http://{{host}}:{{port}}/word/dictWordEn
Content-Type: application/json

{   "model": {    } }

###
POST http://{{host}}:{{port}}/word/listWordEn
Content-Type: application/json

{   "word": "key" }

###







